=== samitheberber/javalabra/ohjelma/xml/avatarrule.dtd
<!ELEMENT AvatarRule (Attributes, Skills, Races)>
<!ELEMENT Attributes (Attribute*)>
<!ELEMENT Attribute (Name)>
<!ELEMENT Skills (Skill*)>
<!ELEMENT Skill (Name)>
<!ELEMENT Races (Race*)>
<!ELEMENT Race (Name)>
<!ELEMENT Name (#PCDATA)>

=== samitheberber/javalabra/ohjelma/sääntö1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AvatarRule SYSTEM "http://www.cs.helsinki.fi/u/saada/kurssit/javalabra/dtd/avatarrule.dtd">
<AvatarRule>
	<Attributes>
		<Attribute>
			<Name>testi</Name>
		</Attribute>
		<Attribute>
			<Name>testi1</Name>
		</Attribute>
	</Attributes>
	<Skills>
		<Skill>
			<Name>testo</Name>
		</Skill>
	</Skills>
	<Races>
		<Race>
			<Name>teste00</Name>
		</Race>
		<Race>
			<Name>tet</Name>
		</Race>
		<Race>
			<Name>etet</Name>
		</Race>
	</Races>
</AvatarRule>
