=== samitheberber/javalabra/ohjelma/xml/avatar.dtd
<!ELEMENT Avatar (Rule, Attributes, Skills, Information)>
<!ELEMENT Rule (#PCDATA)>
<!ELEMENT Attributes (Attribute*)>
<!ELEMENT Attribute (Name, Value)>
<!ELEMENT Skills (Skill*)>
<!ELEMENT Skill (Name, Value)>
<!ELEMENT Information (Name, Player, Race)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Value (#PCDATA)>
<!ELEMENT Player (#PCDATA)>
<!ELEMENT Race (#PCDATA)>

=== samitheberber/javalabra/ohjelma/hahmo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Avatar SYSTEM "http://www.cs.helsinki.fi/u/saada/kurssit/javalabra/dtd/avatar.dtd">
<Avatar>
	<Rule>sääntö1.xml</Rule>
	<Attributes>
		<Attribute>
			<Name>testi</Name>
			<Value>1</Value>
		</Attribute>
		<Attribute>
			<Name>testi1</Name>
			<Value>0</Value>
		</Attribute>
	</Attributes>
	<Skills>
	</Skills>
	<Information>
		<Name>sami</Name>
		<Player>stb</Player>
		<Race>tet</Race>
	</Information>
</Avatar>
